version: '3.6'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petsaur
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: